language: node_js
node_js:
  - 7.0

cache:
  directories:
    - node_modules

os:
  #  # The macOS build in travis is really slow.
  #  - osx
  - linux

# Note that in order to run the tests on Linux,
# you need to have a before_install configuration
# to enable Linux to start VS Code from the build.
# ref https://code.visualstudio.com/Docs/extensions/testing-extensions
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run test

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
